#!/usr/bin/env python3
"""Regenerate _data/schedule.yml from the finance repo's events.csv.

The finance ledger is the operational source of truth for events, so the
website schedule is derived from it instead of being edited by hand:

    python3 scripts/sync_schedule.py          # rewrite _data/schedule.yml
    python3 scripts/sync_schedule.py --check  # exit 1 if schedule.yml is stale

Only PUBLIC fields ever leave the ledger: event_id, name, venue_type and the
run dates. Rent, commission, payees, notes and every other column are never
read. Editorial copy (display name, location, card note) lives in
_data/schedule_overrides.yml, keyed by event_id.

An event appears on the site while it is current or upcoming, and drops off
GRACE_DAYS after it ends. The "On Now" / "Coming Up" badge itself is computed
client-side, so the page stays correct between syncs.

Set NYANMESHI_FINANCE_DIR to point at a different finance repo checkout.
"""

import csv
import os
import re
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

import yaml

SITE_DIR = Path(__file__).resolve().parent.parent
FINANCE_DIR = Path(os.environ.get(
    "NYANMESHI_FINANCE_DIR",
    "/home/common/nyanmeshi_business_materials/nyanmeshi_finance",
))
EVENTS_CSV = FINANCE_DIR / "data" / "events.csv"
SCHEDULE_YML = SITE_DIR / "_data" / "schedule.yml"
OVERRIDES_YML = SITE_DIR / "_data" / "schedule_overrides.yml"

PUBLIC_FIELDS = {"event_id", "name", "venue_type", "start", "end"}
GRACE_DAYS = 3

VENUE_TYPE_DISPLAY = {
    "Pasar Malam": "Pasar Malam",
    "Festival": "Festival",
    "Dept store": "Department Store",
}


def parse_date(s):
    return datetime.strptime(s.strip(), "%Y-%m-%d").date()


def dates_display(start, end):
    if start.year != end.year:
        return f"{start.day} {start:%B %Y} – {end.day} {end:%B %Y}"
    if start.month != end.month:
        return f"{start.day} {start:%B} – {end.day} {end:%B} {end.year}"
    return f"{start.day} – {end.day} {end:%B %Y}"


def dates_display_ja(start, end):
    if start.year != end.year:
        return f"{start.year}年{start.month}月{start.day}日〜{end.year}年{end.month}月{end.day}日"
    if start.month != end.month:
        return f"{start.year}年{start.month}月{start.day}日〜{end.month}月{end.day}日"
    return f"{start.year}年{start.month}月{start.day}日〜{end.day}日"


def yq(s):
    """Quote a string for YAML output."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_entries(today):
    overrides = {}
    if OVERRIDES_YML.exists():
        overrides = yaml.safe_load(OVERRIDES_YML.read_text()) or {}

    entries = []
    with open(EVENTS_CSV, newline="") as f:
        for row in csv.DictReader(f):
            public = {k: row.get(k, "").strip() for k in PUBLIC_FIELDS}
            try:
                start, end = parse_date(public["start"]), parse_date(public["end"])
            except ValueError:
                continue
            if end < today - timedelta(days=GRACE_DAYS):
                continue
            ov = overrides.get(public["event_id"], {}) or {}
            name = ov.get("name") or public["name"]
            if "name" not in ov and public["venue_type"] == "Pasar Malam":
                name = f"{name} Pasar Malam"
            entries.append({
                "event_id": public["event_id"],
                "csv_name": public["name"],
                "map_skip": bool(ov.get("map_skip")),
                "name": name,
                "name_ja": ov.get("name_ja", ""),
                "type": VENUE_TYPE_DISPLAY.get(public["venue_type"], public["venue_type"]),
                "location": ov.get("location", "Singapore"),
                "location_ja": ov.get("location_ja", ""),
                "start": start,
                "end": end,
                "dates_display": dates_display(start, end),
                "dates_display_ja": dates_display_ja(start, end),
                "note": ov.get("note", ""),
                "note_ja": ov.get("note_ja", ""),
            })
    entries.sort(key=lambda e: e["start"])
    return entries


def render(entries, today):
    lines = [
        "# GENERATED by scripts/sync_schedule.py from the finance repo's events.csv",
        f"# (synced {today.isoformat()}). Do not edit by hand — editorial copy goes in",
        "# _data/schedule_overrides.yml; then re-run the script.",
    ]
    for e in entries:
        lines.append(f"- event_id: {e['event_id']}")
        lines.append(f"  name: {yq(e['name'])}")
        if e["name_ja"]:
            lines.append(f"  name_ja: {yq(e['name_ja'])}")
        lines.append(f"  type: {yq(e['type'])}")
        lines.append(f"  location: {yq(e['location'])}")
        if e["location_ja"]:
            lines.append(f"  location_ja: {yq(e['location_ja'])}")
        lines.append(f"  start: {e['start'].isoformat()}")
        lines.append(f"  end: {e['end'].isoformat()}")
        lines.append(f"  dates_display: {yq(e['dates_display'])}")
        lines.append(f"  dates_display_ja: {yq(e['dates_display_ja'])}")
        if e["note"]:
            lines.append(f"  note: {yq(e['note'])}")
        if e["note_ja"]:
            lines.append(f"  note_ja: {yq(e['note_ja'])}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def missing_map_markers(entries):
    """Events with no marker on the footprint map (override with map_skip)."""
    locations_yml = SITE_DIR / "_data" / "locations.yml"
    markers = yaml.safe_load(locations_yml.read_text()) or []
    marker_tokens = set()
    for m in markers:
        marker_tokens.update(w for w in re.findall(r"[a-z]+", m["name"].lower()) if len(w) >= 5)

    missing = []
    for e in entries:
        if e["map_skip"]:
            continue
        tokens = {w for w in re.findall(r"[a-z]+", e["csv_name"].lower()) if len(w) >= 5}
        if not tokens & marker_tokens:
            missing.append(e)
    return missing


def report_map_coverage(entries):
    missing = missing_map_markers(entries)
    for e in missing:
        print(f"MAP: no marker for '{e['csv_name']}' ({e['event_id']}) — add it to "
              "_data/locations.yml (name/lat/lng/type), or set 'map_skip: true' in "
              "_data/schedule_overrides.yml if it is outside Singapore.")
    return missing


def main():
    if not EVENTS_CSV.exists():
        sys.exit(f"events.csv not found at {EVENTS_CSV} — set NYANMESHI_FINANCE_DIR")
    today = date.today()
    entries = build_entries(today)
    new = render(entries, today)

    if "--check" in sys.argv:
        old = SCHEDULE_YML.read_text() if SCHEDULE_YML.exists() else ""
        # ignore the dated header when comparing
        strip = lambda t: "\n".join(l for l in t.splitlines() if not l.startswith("#"))
        stale = strip(old) != strip(new)
        if stale:
            print("schedule.yml is STALE — run: python3 scripts/sync_schedule.py")
        missing = report_map_coverage(entries)
        if stale or missing:
            sys.exit(1)
        print("schedule.yml is up to date; map covers all scheduled events")
        return

    SCHEDULE_YML.write_text(new)
    print(f"wrote {SCHEDULE_YML.relative_to(SITE_DIR)}:")
    print(new)
    report_map_coverage(entries)


if __name__ == "__main__":
    main()
